### ISSUE TITLE
Compatibility with Nuxt 4

### ISSUE THREAD

**Issue by Gobler** [prisma/nuxt-prisma#20] opened 2024-07-17 08:19 UTC
Nuxt 4(or running in compatibility mode) has a new application structure - unfortunately, at the moment the module does not support the new structure and it is not possible to run the application with the module active.

**Comment by Gobler** [comment] 2024-07-17 08:50
I see that the above problem is probably related to https://github.com/prisma/nuxt-prisma/issues/15 - I using pnpm and in addition it is working with monorepo and nuxt layers... 

will test it a bit more but I also get an "ERROR  ✘ Failed to install Prisma Client." error and everything crashes

**Comment by ankur-arch** [comment] 2024-07-29 13:49
Hey @Gobler there's a PR to fix #15 , I'm working on merging it in and then we can see if this gets resolved.

**Comment by ankur-arch** [comment] 2024-08-02 12:34
Hey @Gobler the PR has been [merged](https://github.com/prisma/nuxt-prisma/issues/15#issuecomment-2265225834), can see if it the crash is resolved?

Plus could you provide a minimal reproduction for your issue?

**Comment by husayt** [comment] 2024-08-03 23:33
I am getting this error while using prisma with pnpm  workspaces.
The project is a nuxt layer extending another nuxt app from the same workspace with prisma functionality

![image](https://github.com/user-attachments/assets/7534aff1-0224-4423-89c5-797b112d7463)

**Comment by Dobefu** [comment] 2024-08-04 20:35
Hi @husayt!

Not sure if this helps, but I know that `npm` gets used over other package managers if there are multiple lockfiles. This might be what is happening here, but I'm missing some information. If you happen to have both a `package-lock.json` and a `pnpm-lock.yaml`, does the issue still occur after deleting the `package-lock.json`?

**Comment by husayt** [comment] 2024-08-04 20:37
Thank you, but I don't use npm, so I don't have package.lock

**Comment by Dobefu** [comment] 2024-08-04 20:41
My goodness, that's a quick response 🙂.
The error would suggest that the code is calling the `npm` command somewhere. It's nighttime for me now, so I can look tomorrow. But do you happen to have a minimal reproduction?

**Comment by husayt** [comment] 2024-08-04 20:44
I will try to come up with repro, but in case if someone came across this will be good to hear from them

**Comment by Dobefu** [comment] 2024-08-05 08:41
Ah, I think I see what is happening now. Here's the relevant code for the issue:

```js
function detectPackageManager(): PackageManager {
  // Check for package-lock.json
  if (existsSync("package-lock.json")) {
    return "npm";
  }

  // Check for yarn.lock
  if (existsSync("yarn.lock")) {
    return "yarn";
  }

  // Check for pnpm-lock.yaml
  if (existsSync("pnpm-lock.yaml")) {
    return "pnpm";
  }

  // bun.lockb
  if (existsSync("bun.lockb")) {
    return "bun";
  }

  // Default to npm if none of the above are found
  return "npm";
}
```

I see two things happening here:
1. The function only looks in the current directory
2. The fallback does not print a warning, which might be desirable

I will check if I can create a minimal reproduction, and link a repo containing said reproduction.

**Comment by Dobefu** [comment] 2024-08-05 10:17
I've managed to reproduce the issue in Nuxt 3. I'll create a new issue, since it doesn't appear to be a Nuxt 4 issue

**Comment by ankur-arch** [comment] 2024-08-06 09:00
Thanks for jumping in @Dobefu , closing this in favour of #29.

**Closed by ankur-arch** 2024-08-06 09:00 UTC

**Comment by andreakru** [comment] 2024-12-13 11:16
I am testing the module with Nuxt 4 but I got an error. Is there any specific branch I have to use?

**Comment by arshx86** [comment] 2025-07-28 20:31
> I am testing the module with Nuxt 4 but I got an error. Is there any specific branch I have to use?
> 
> [@ankur-arch](https://github.com/ankur-arch)
> 
> Error when running `pnpm dev` after installation
> 
> ✘ [ERROR] Could not resolve ".prisma/client/index-browser"
> 
> ```
> node_modules/.pnpm/@prisma+client@5.22.0_prisma@6.0.1/node_modules/@prisma/client/index-browser.js:1:23:
>   1 │ const prisma = require('.prisma/client/index-browser')
>     ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> You can mark the path ".prisma/client/index-browser" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> 
> ERROR [unhandledRejection] Build failed with 1 error: 12:18:17 PM node_modules/.pnpm/[@prisma](https://github.com/prisma)+client@5.22.0_prisma@6.0.1/node_modules/@prisma/client/index-browser.js:1:23: ERROR: Could not resolve ".prisma/client/index-browser"
> 
> node_modules/.pnpm/[@prisma](https://github.com/prisma)+client@5.22.0_prisma@6.0.1/node_modules/@prisma/client/index-browser.js:1:23: ERROR: Could not resolve ".prisma/client/index-browser" at failureErrorWithLog (node_modules/.pnpm/esbuild@0.24.0/node_modules/esbuild/lib/main.js:1476:15) at node_modules/.pnpm/esbuild@0.24.0/node_modules/esbuild/lib/main.js:945:25 at node_modules/.pnpm/esbuild@0.24.0/node_modules/esbuild/lib/main.js:1354:9 at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

are you managed to fix??
