### ISSUE TITLE
Prisma can only run debugging, cannot compile and publish?

### ISSUE THREAD

**Issue by bbhxwl** [prisma/nuxt-prisma#14] opened 2024-06-24 02:02 UTC
Prisma can only run debugging, cannot compile and publish?
I can run it, but will the npm run build make an error?

![image](https://github.com/prisma/nuxt-prisma/assets/26525599/38815388-bb72-439a-900b-14b0af3e4eb3)

```
".prisma/client/index-browser" is imported by ".prisma/client/index-browser?commonjs-external", but could not be resolved – treating it as an external dependency.

[09:40:37]  WARN  [plugin:vite:esbuild] [plugin vite:esbuild] components/adl/form/index.vue?vue&type=script&setup=true&lang.ts: The "??" operator here will always return the left operand
251|      (__props.addApiName)
252|        ? (_openBlock(), _createElementBlock(_Fragment, { key: 0 }, [
253|            (__props.btnConfirmType!=='link'??_unref(store).globalSettings.addButtonStyle==='1')
   |                                            ^
254|              ? (_openBlock(), _createBlock(_component_lazy_el_button, _mergeProps({ key: 0 }, _ctx.$attrs, {       
255|                  plain: "",



[09:40:37]  WARN  [plugin:vite:esbuild] [plugin vite:esbuild] components/adl/form/index.vue?vue&type=script&setup=true&lang.ts: The "??" operator here will always return the left operand
263|                }, 16, ["type"]))
264|              : _createCommentVNode("", true),
265|            (__props.btnConfirmType==='link'??_unref(store).globalSettings.addButtonStyle==='2')
   |                                            ^
266|              ? (_openBlock(), _createBlock(_component_lazy_el_link, _mergeProps({ key: 1 }, _ctx.$attrs, {
267|                  type: __props.btnType??'primary',



 ERROR  x Build failed in 11.60s                                                                              09:40:44  


[09:40:44]  ERROR  Nuxt Build Error: [vite]: Rollup failed to resolve import "D:/project/git/ADLWebNuxt3/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3" from "virtual:nuxt:D:/project/git/ADLWebNuxt3/.nuxt/plugins/client.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  build.rollupOptions.external
  at viteWarn (/D:/project/git/ADLWebNuxt3/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65810:17)
  at onRollupWarning (/D:/project/git/ADLWebNuxt3/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65845:5)
  at onwarn (/D:/project/git/ADLWebNuxt3/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65505:7)
  at /D:/project/git/ADLWebNuxt3/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18514:13
  at Object.logger [as onLog] (/D:/project/git/ADLWebNuxt3/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:20162:9)
  at ModuleLoader.handleInvalidResolvedId (/D:/project/git/ADLWebNuxt3/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19104:26)
  at /D:/project/git/ADLWebNuxt3/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19062:26

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

**Comment by jharrell** [comment] 2024-06-24 18:51
Duplicate of #12

**Closed by jharrell** 2024-06-24 18:51 UTC
