### ISSUE TITLE
Module uses root folder *always*

### ISSUE THREAD

**Issue by Harm-Nullix** [prisma/nuxt-prisma#32] opened 2024-08-09 08:37 UTC
So I have the structure of the following in my _nuxt.config_:

```
  serverDir: path.resolve('./src/backend'),
  rootDir: path.resolve('.'),
  srcDir: path.resolve('./src'),
  dir: {
    assets: path.resolve('./src/frontend/assets'),
    plugins: path.resolve('./src/frontend/plugins'),
    middleware: path.resolve('./src/frontend/middleware'),
    layouts: path.resolve('./src/frontend/layouts'),
    pages: path.resolve('./src/frontend/pages'),
    public: path.resolve('./src/backend/public'),
    static: path.resolve('./src/backend/public'),
  },
```

This works for everything well, but this module insist on using the rootDir. 
It would be really nice if that would be configurable, because I have my prisma files stored in the backend folder instead of at the root.

Cause of pain: https://github.com/prisma/nuxt-prisma/blob/main/src/module.ts#L65

**Comment by ankur-arch** [comment] 2024-08-09 10:07
Hey @Harm-Nullix 👋 , thanks for reporting the issue! We plan to make the module usable with the prisma files being on a separate directory.

**Comment by ankur-arch** [comment] 2024-10-18 09:40
Duplicate of #16

**Closed by ankur-arch** 2024-10-18 09:40 UTC
Labels: enhancement, nuxt
